### PR TITLE
coco-cs

### PR DESCRIPTION
**Pull request by Tovim**
Hi Evan, my previous commit tov-cs was incorporated into GitHub properly but apparently it wasn´t propagated into RTD. Now I am sending you a slightly modified one. I am looking forward to see it at the RTD.
I feel a little bit uncomfortable having to bother you with my needs. I am very gratefull to you for it.
Jaroslav

### CODE REVIEW

**Comment by evhub** [comment]
@Tovim Your branch conflicts with master; can you `git pull` with `--rebase` so I can merge cleanly?

**Comment by evhub** [comment]
@Tovim If you want, I can add you as a contributor on this repository, so you can merge your own pull requests without needing me to approve them.

**Comment by Tovim** [comment]
Hi, I have made as I was navigated. Maybe, it is OK now.
Being an approved contributor would be nice.

**Comment by evhub** [comment]
@Tovim Just sent you an invite!

**Comment by Tovim** [comment]
Thank you very much. I think I will use it  occasionally:
-  when correcting  or making my translations better
-  adding new translations when needed
I suppose you will send me a message after you will have changed or added something to your documentation.
Please tell me, do you have a githook between GitHub and RTD arranged?
Jaroslav

**Comment by evhub** [comment]
@Tovim Sounds good! And yes, there is a hook--RTD should build whenever `master` here is updated. As for what has changed recently in the documentation, if you check out the [release log](https://github.com/evhub/coconut/releases) you can see what new things have been added recently, and translate the corresponding documentation if you want to.

**Comment by Tovim** [comment]
So RTD will build, whenever master  (meaning evhub/coconut?) will be updated. Which means that updating evhub/coco-cs only is not enough? This I have done just little while ago.
Jaroslav

**Comment by evhub** [comment]
@Tovim No, it should build whenever the master branch of **this repository** (coco-cs) is updated.

**Comment by Tovim** [comment]
@evhub, me seems that the hook doesn´t work properly, anyway. Looking at coconut.readthedocs.io/cs/master/README.html, we are greeting with an older version "Coconut 1.2.1". Activating "On Github/View in the same page, we can read the commit message "latest instead master" which is (now) about 30 min. old.
Visiting my test-project potomek/cocos (potomek.readthedocs.io/cs/latest), we can see the proper heading "Coconut 1.2.2 and everything else being spick and span.
Aside Note: Links in coconut are something like "coconut.rtd.org/en/**master**/DOCS.html" whereas in coco-cs they have to be "coconut.rtd.org/cs/**latest**/DOCS.html. This was a somewhat "long way to Tipperary" for me to find the proper wording out.
I wish the hooks were working.
Jaroslav

**Comment by evhub** [comment]
@Tovim I think I found a problem with the hook--try now!

**Comment by Tovim** [comment]
Hallelujah, it is working! Thank you.
Tovim

**Pull request closed without merging**
